### ISSUE TITLE
PRs are not closed - and UnhandledPromiseRejectionWarning warning 

### ISSUE THREAD

**Issue by mjacobus** [lee-dohm/close-matching-issues#353]
Hey Lee 👋🏻 

I haven't been able to have this action close PRs. This is probably a silly misconfig of mine. But just in case this is a bug, I am opening this issue.

#### Here is the action:

```yml
name: Auto-close stale batch PRs

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '33 18 * * *' # every day at 18:33 UTC at least until automerge is working

jobs:
  auto-close-stale-prs:
    name: Auto close Stale batch PRs
    runs-on: ubuntu-latest

    steps:
      - name: Close stale batch
        uses: lee-dohm/close-matching-issues@22002609b2555fe18f52b8e2e7c07cbf5529e8a8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: 'label:translation-batch-dummy'
```

#### I now there is a PR matching that label:

![image](https://user-images.githubusercontent.com/226834/146049030-b3004229-5b09-4250-88b7-7277c8718a0e.png)

#### But when the action runs, it does not close anything. Plus, there is a warning:

```
Run lee-dohm/close-matching-issues@22002609b2555fe18f52b8e2e7c07cbf5529e8a8
  with:
    token: ***
    query: label:translation-batch-dummy
(node:1494) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/lee-dohm/close-matching-issues/22002609b2555fe18f52b8e2e7c07cbf5529e8a8/dist/index.js:4406:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Here is an image

![image](https://user-images.githubusercontent.com/226834/146049290-17c7e3e6-10a1-4161-a239-24e8ecffc0ec.png)

Did you spot any error on my config, or is this a bug?
